name: Update Runner Version
on:
  push:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight

env:
  IMAGE_NAME: self-hosted-actions-runner

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch latest runner version
        id: latest_version
        run: |
          echo "LATEST_VERSION=$(curl --silent "https://api.github.com/repos/actions/runner/releases/latest" | jq -r .tag_name | cut -c 2-)" >> $GITHUB_ENV

      - name: Get current runner version
        id: current_version
        run: |
          echo "CURRENT_VERSION=$(curl --silent -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" "https://ghcr.io/v2/${{ github.repository }}/${{ env.IMAGE_NAME }}/tags/list" | jq -r '.tags[]' | sort -V | tail -n 1)" >> $GITHUB_ENV

      - name: Compare versions
        id: compare_versions
        run: |
          if [ "${{ env.LATEST_VERSION }}" != "${{ env.CURRENT_VERSION }}" ]; then
            echo "SHOULD_BUILD=true" >> $GITHUB_ENV
          else
            echo "SHOULD_BUILD=false" >> $GITHUB_ENV
          fi

      - name: Build Docker image
        if: env.SHOULD_BUILD == 'true'
        run: |
          docker build . --build-arg RUNNER_VERSION=${{ env.LATEST_VERSION }} --tag ${{ env.IMAGE_NAME }}:${{ env.LATEST_VERSION }}

      - name: Login to GitHub Container Registry
        if: env.SHOULD_BUILD == 'true'
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
  
      - name: Push Docker image
        if: env.SHOULD_BUILD == 'true'
        run: |
          docker tag ${{ env.IMAGE_NAME }}:${{ env.LATEST_VERSION }} ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ env.LATEST_VERSION }}
          docker push ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ env.LATEST_VERSION }}
          docker tag ${{ env.IMAGE_NAME }}:${{ env.LATEST_VERSION }} ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}:latest
          docker push ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}:latest
