name: Update Runner Version
on:
  push:
  workflow_dispatch: # Allows manual triggering
  schedule:
    - cron: '0 0 * * *' # Runs every day at midnight

env:
  IMAGE_NAME: self-hosted-actions-runner

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Fetch latest runner version
        id: latest_version
        run: |
          echo "::set-output name=version::$(curl --silent "https://api.github.com/repos/actions/runner/releases/latest" | jq -r .tag_name | cut -c 2-)"

      - name: Get current runner version
        id: current_version
        run: |
          echo "::set-output name=version::$(cat .runner_version)"

      - name: Compare versions
        id: compare_versions
        run: |
          if [ "${{ steps.latest_version.outputs.version }}" != "${{ steps.current_version.outputs.version }}" ]; then
            echo "::set-output name=should_build::true"
            echo "${{ steps.latest_version.outputs.version }}" > .runner_version
          else
            echo "::set-output name=should_build::false"
          fi

      - name: Build Docker image
        if: steps.compare_versions.outputs.should_build == 'true'
        run: |
          docker build . --build-arg RUNNER_VERSION=${{ steps.latest_version.outputs.version }} --tag ${{ env.IMAGE_NAME }}:${{ steps.latest_version.outputs.version }}

      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
  
      - name: Push Docker image
        run: |
          docker tag ${{ env.IMAGE_NAME }}:${{ steps.latest_version.outputs.version }} ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ steps.latest_version.outputs.version }}
          docker push ghcr.io/${{ github.repository }}/${{ env.IMAGE_NAME }}:${{ steps.latest_version.outputs.version }}
